version: '3.7'

volumes:
  data:
services:
  pgsql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      USERNAME: postgres
      POSTGRES_DB: allspace
      POSTGRES_PASSWORD: allspace
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo: #https://hub.docker.com/_/mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: allspace
      MONGO_INITDB_ROOT_PASSWORD: allspace
      MONGO_INITDB_DATABASE: allspace
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: allspace
      ME_CONFIG_MONGODB_ADMINPASSWORD: allspace
  backend:
    build:
      context: .
      args:
        uid: ${UID}
    env_file:
      - .env
    volumes:
      - '.:/app'
    ports:
      - '9229:9229'
      - '3333:3333'
    links:
      - pgsql
      - mongo
    command: sh -c "yarn install && yarn build && yarn typeorm migration:run && yarn dev:server"
